# Generated by Django 5.2.7 on 2025-10-08 04:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaivariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('choices', models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('TL', 'Tulsi'), ('KL', 'KIWI'), ('PL', 'Plain'), ('EL', 'Elaichi')], max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
